name: flutter_svg
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository: https://github.com/dnfield/flutter_svg/tree/master/packages/flutter_svg
issue_tracker: https://github.com/dnfield/flutter_svg/issues
publish_to: none
version: 2.0.7

dependencies:
  flutter:
    sdk: flutter

  vector_graphics:
    git:
      url: https://github.com/XperiTech/vector_graphics
      path: packages/vector_graphics
      ref: da1232d4f70d0b55b10b10de94740723179cfff7
  vector_graphics_codec:
    git:
      url: https://github.com/XperiTech/vector_graphics
      path: packages/vector_graphics_codec
  vector_graphics_compiler:
    git:
      url: https://github.com/XperiTech/vector_graphics
      path: packages/vector_graphics_compiler

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.19.0-0 <4.0.0'
  flutter: ">=3.7.0-0"